<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MonctonEventsNet.Application.EpPlus\MonctonEventsNet.Application.EpPlus.csproj" />
      <ProjectReference Include="..\MonctonEventsNet.Application\MonctonEventsNet.Application.csproj" />
      <ProjectReference Include="..\MonctonEventsNet.Infrastructure\MonctonEventsNet.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Data\" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Data\What's Happening in Greater Moncton.xlsx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
